//
//  TempuraSceneProtocols.swift
//  nn_pickers
//
//  Created Tran Khoa on 29/6/18.
//  Copyright © 2018 app_modules. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol TempuraSceneWireframeProtocol: class {

}
//MARK: Presenter -
protocol TempuraScenePresenterProtocol: class {

    var interactor: TempuraSceneInteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol TempuraSceneInteractorOutputProtocol: class {

    /* Interactor -> Presenter */
}

protocol TempuraSceneInteractorInputProtocol: class {

    var presenter: TempuraSceneInteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol TempuraSceneViewProtocol: class {

    var presenter: TempuraScenePresenterProtocol?  { get set }

    /* Presenter -> ViewController */
}
