//
//  TempuraSceneViewController.swift
//  nn_pickers
//
//  Created Tran Khoa on 29/6/18.
//  Copyright © 2018 app_modules. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit
import SnapKit
class TempuraSceneViewController: UIViewController, TempuraSceneViewProtocol {

	var presenter: TempuraScenePresenterProtocol?

    
    var IAMString:String!
    var IAM:UILabel = UILabel()

    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = #colorLiteral(red: 1.0, green: 1.0, blue: 1.0, alpha: 1.0)
        let btn = UIButton()
        btn.setTitle("hello", for: .normal)
        view.addSubview(btn)
        btn.addTarget(self, action: #selector(btnTapped), for: UIControlEvents.touchUpInside)
    }
    
    
    
    @objc func btnTapped(){
        
    }
    
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        view.addSubview(IAM)
        IAM.text = IAMString
        IAM.snp.makeConstraints { (make) in
            make.center.equalToSuperview()
        }
    }

}
