//
//  TempuraSceneInteractor.swift
//  nn_pickers
//
//  Created Tran Khoa on 29/6/18.
//  Copyright © 2018 app_modules. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class TempuraSceneInteractor: TempuraSceneInteractorInputProtocol {

    weak var presenter: TempuraSceneInteractorOutputProtocol?
}
